### ISSUE TITLE
Front Product View - Product Details Section

### ISSUE THREAD

**Issue by diksha-cedcoss** [PrestaShop/hummingbird#125]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Is your feature request related to a problem?

First of all, I would like to say it's not a bug, it's an enhancement request.

If you will view any product, in the product details section, you can see that at the top manufacturer image & its link is given that we can assign it to the left-top corner as it consumes a lot of space & doesn't look so good.

I have attached the screenshot of the actual view :

[
![Product_detail_view](https://user-images.githubusercontent.com/40261082/142624278-c56fc127-a7f8-420c-931e-b4912dd2c078.png)
](url)

### Describe the solution you'd like

We can shift the manufacturer image to the right-top corner & shift other fields to the top to reduce more space & enhance its look.

I did this to show you how I mean :

[
![Product_view_suggestion](https://user-images.githubusercontent.com/40261082/142624671-edbea9a6-dc7d-4e00-b318-ffb1910975e7.png)
](url)

### Steps to reproduce

1. Go to 'Your Prestashop Website'
2. Open any product to view the product data
3. Move down to the 'Product Details' section
4. You can view the 'Manufacturer' data & other data in that section

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by Hlavtox** [comment]
@prestascott Put brand's textual name and slap the logo on the right top, done ;-)

**Comment by alfonsolr09** [comment]
> **EXPAND**
> ![image](https://user-images.githubusercontent.com/54888056/143425122-3c5f2da3-210e-4661-9f84-f4471bb7d14b.png)

What do you think about putting the product details in two columns? Now it looks very lonely and if there are many features it will look very long. I think it would be a good idea to lay it out in two columns or to try find a different idea ...

**Comment by prestascott** [comment]
@alfonsolr09 What features do you have in mind?

**Comment by alfonsolr09** [comment]
I mean product characteristics.

**Comment by NeOMakinG** [comment]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/14963751/182869856-578a4f60-00f7-4aed-8552-17fa5483b979.png">

Can be closed as the new design has been integrated!
