### ISSUE TITLE
[Component] Product list : add an add to cart button

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/hummingbird#132]
It was there in 1.6.
You can add it this way 
https://www.matthieu-jalbert.fr/afficher-un-bouton-ajouter-au-panier-sur-le-listing-produit-de-prestashop-1-7/

There are tocken issues on home page modules with cache, issues are on prestashop github.

**Comment by Hlavtox** [comment]
@jf-viguier I would like to do it and many merchants want it, but product team has the final word, unfortunately. :-)

There is one problem with this, if you have disabled ordering out of stock products, it allows you to add more items to cart, than you have in stock. :(

**Comment by alfonsolr09** [comment]
> @ jf-viguier Me gustaría hacerlo y muchos comerciantes lo quieren, pero el equipo de producto tiene la última palabra, desafortunadamente. :-)
> 
> Hay un problema con esto, si ha inhabilitado el pedido de productos agotados, le permite agregar más artículos al carrito de los que tiene en stock. :(

can there be the same solution as on the product page?

**Comment by jf-viguier** [comment]
> @jf-viguier I would like to do it and many merchants want it, but product team has the final word, unfortunately. :-)
> 
> 
> 
> There is one problem with this, if you have disabled ordering out of stock products, it allows you to add more items to cart, than you have in stock. :(

Where is the issue ?
It's time to fix it

**Comment by Hlavtox** [comment]
https://github.com/PrestaShop/PrestaShop/issues/23496

**Comment by NeOMakinG** [comment]
Closing in favor of https://github.com/PrestaShop/hummingbird/issues/347
