### ISSUE TITLE
[RESPONSIVE - Checkout Page] Order confirmation

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/hummingbird#16]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=2365%3A26777)

**Comment by NeOMakinG** [comment]
I guess this is done, if there are some things to polish, let's see this after product review
