### ISSUE TITLE
Improve input-number spin buttons for mobile

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/hummingbird#173]
### Mobile Usability report - Google Support
**Clickable elements too close together**
Touch elements, such as buttons and navigational links, are so close to each other that a mobile user cannot easily tap a desired element with their finger without also tapping a neighboring element. 

So I think we can have two different UI for input-number:

| Desktop  | Mobile |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/85633460/152979775-4d78b38e-737c-4c6c-952c-319d0c9ac554.png">  | <img src="https://user-images.githubusercontent.com/85633460/152979859-e6624ad1-571d-43e4-80a1-2a8220c97ab4.png"> |

**Comment by SharakPL** [comment]
IMO they should be the same everywhere, so mobile version also on desktops. One improvement though: they should be styled as buttons and not look the same as inputs. Default BS5 [button addons](https://getbootstrap.com/docs/5.1/forms/input-group/#button-addons) should be used for this.

**Comment by mparvazi** [comment]
I used BS5 button-addons for demo images.
Button's text replaced with material-icons.

Btw it's easy to change input-number style with BS5 on different media screens, there is no need for extra javascript or css.

**Comment by NeOMakinG** [comment]
The simplest is the best, I would go for the mobile options on both desktop and mobile, it's clean on both, it's easy to maintain, no library needed, smallest JS in order to make it work

https://build.prestashop.com/prestashop-ui-kit/?path=/story/forms--number

We already have the JS logic in the core too

**Comment by NeOMakinG** [comment]
@prestascott

**Comment by adamus007p** [comment]
I would like to give a suggestion. The last may look better but, we need to remember that in some languages Add to card it is much longer and there may be some problems. Please try to add German or Swedish translation.

Color: write > there is no space after S

Quantity: everywhere is :


Share buttons. I was thinking if this is the best place put this buttons close, customer can quit during process and stay in Facebook and do not return to the shop. This is potential exit point.


I would separate Share icons, the main goal is that customer should add to card and go to payment step.

This heart icon could go near to photo. To many icons near to Add to cart button.

Quantity I would keep in one line, as we can add with it some info 1 from 100 available for example, if someone would want to show quantity.

If you want to keep hear icon I am sending you two ideas.

![image](https://user-images.githubusercontent.com/19956106/153037859-9e5f0b5d-fd2f-4fb5-a5f2-0f5bacb7b565.png)


Share buttons I would make some line or space from add to cart button.

**Comment by adamus007p** [comment]
PPS. In desktop I would keep the same rule: one line one customer decision.

The heart button I would keep near or on the image. What customers like? The title of the product, not, mostly the photo, video, audio.


In this way we could separate the customer who is in the progress of buying and someone who just looking.

After Add to card I would add some trust buttons, or some manufacture details etc.

**Comment by mparvazi** [comment]
1. Wishlist icon placement:
It's realated to blockwishlist module and hooks.

2. Padding, Margins, and Share icons, ...
Theme isn't completed yet, so minor bugs like these will be fixed.

3. Qty input width in small media
I think it should be in a separate row, because more icons can be added by other modules next to the "Add to Cart" button.

**Comment by SharakPL** [comment]
> 3. Qty input width in small media
> I think it should be in a separate row, because more icons can be added by other modules next to the "Add to Cart" button. 
> 

👍 Exactly. The only possible addition to the row with quantity and _Add to cart_ button would be ⚙️ _Customize_ button if product provides customization. It could activate a modal with customization form. Unless this form is going to be loaded straight away next to other attributes.

Good place for ❤️ _Add to wishlist_ button is next to product name.

Other buttons should be placed elsewhere. Maybe next to social follow buttons.

**Comment by prestascott** [comment]
Hello everyone 👋

Thanks for your request, here is my design proposition:

## Cart page
<img width="375" alt="MOBILE - Cart page (1)" src="https://user-images.githubusercontent.com/54888056/153421529-7910a13c-0acd-4c30-81c2-c5d1030ac4fc.png">

- The number input is way bigger and easier to interact with
- The spacing between attributes have been increased to avoid misclicks


## Product page with wishlist

Product not added to wishlist
<img width="375" alt="MOBILE - Product page - disabled" src="https://user-images.githubusercontent.com/54888056/153421895-16408640-49ea-4413-8e94-7d8514b5d4cc.png">
- The icon is placed next to the product name, and also thumb-friendly
- The product isn't added to wishlist, so the icon is outlined


Product added to wishlist
<img width="375" alt="MOBILE - Product page - disabled (1)" src="https://user-images.githubusercontent.com/54888056/153421898-cc10315f-405c-4a25-b8e4-116085b651be.png">
- The icon becomes red


Wdyt?

**Comment by SharakPL** [comment]
@prestascott don't you think - / + should look different from quantity input? Styling like that is good only for a group of buttons and we have 2 different components here.

**Comment by adamus007p** [comment]
- / + should look different from quantity input?
@SharakPL what you mean?

The thing is is really needed and in how many percent customers will buy more than one piece?
Maybe in some business they order more pieces, but in general not. One laptop, one book or t-shirt.

Should we attract the eyes into this?

**Comment by adamus007p** [comment]
What happen in mobile when someone will click on wishlist. And it is not logged in?

**Comment by adamus007p** [comment]
@SharakPL does hover works on mobile?

**Comment by SharakPL** [comment]
On that I agree. Main buttons in components should always use `btn-primary`, just like _Add to cart_ does.
`btn-outline-primary` is better for _Cancel_, _Continue shopping_, etc.

**Comment by SharakPL** [comment]
> The thing is if it is really needed? From my experience 99% of customers do not use it.

Prestashop is made for all kinds of products. Some of them may require big quantity numbers. Just because you don't need it doesn't mean others also won't. So it always should provide - / +. I buy mostly online these days and I've used these buttons a lot on different stores.

Only improvement I can think of is when there's only 1 item available in stock. In this case Quantity could be hidden or just say **Last item!**

**Comment by SharakPL** [comment]
![addtocart](https://user-images.githubusercontent.com/5007456/153586265-cfe5035c-090e-441f-bdc3-173dabe7b862.gif)

Actually making it this way would be huge improvement. It would be much easier to keep track on products and quantities already in the cart. Even when there will be cart offcanvas available on every page, sometimes cart has a lot of products so it's still hard to keep track. But this way every time you visit a product page or category, you would get just a button

`Add to cart`

for products you don't yet have in your cart or

`-` [amount in the cart] `+`

**Comment by adamus007p** [comment]
@SharakPL how may I contact with you? May you give me an email?

**Comment by NeOMakinG** [comment]
@mparvazi I guess we can close this issue as the input number component has been merged? Feel free to open it again if I was wrong
