### ISSUE TITLE
Support Font Awesome 6

### ISSUE THREAD

**Issue by DracoBluee** [PrestaShop/hummingbird#174]
Icon support FontAwesome 6

**Comment by SharakPL** [comment]
How about Bootstrap Icons?

**Comment by NeOMakinG** [comment]
Actually, we use material icons, this is a choice from the designer @prestascott 

We will support only one font, I don't mind about which one myself

**Comment by mparvazi** [comment]
FontAwesome would be troublesome for RTL icon mirroring.
Currently we can manage icon mirroring for RTL inside templates for material-icons.

**Comment by DracoBluee** [comment]
FontAwesome or bootstrap alternatively google icon

**Comment by NeOMakinG** [comment]
Closing in favor of https://github.com/PrestaShop/hummingbird/issues/205
