### ISSUE TITLE
[DESKTOP - My account Page] GDPR - Personal data

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/hummingbird#24]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2
Responsive's issue: https://github.com/PrestaShop/theme-refacto/issues/30

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=236%3A10538)

#### UX and design explanations
- A "download" icon has been added to both "Get my data to PDF" and "Get my data to CSV" button to emphasize that it's downloadable

#### Mockup
![desktop - gdpr personal data](https://user-images.githubusercontent.com/54888056/138281627-9aec617e-5cf8-45d6-ae8a-9c0c7e6e0dea.png)

**Comment by NeOMakinG** [comment]
> Will it be option to delete account too? @prestascott @NeOMakinG
> 
> If not such option would be convinient as many customers ask to close/delete account.

I guess this is something you should ask by creating an issue on the core side as we need a way to implement this in the core before
