### ISSUE TITLE
Material Icons are not aligned vertically inside the buttons

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/hummingbird#241]
**Current (the icon and the text are not aligned vertically when icons are not inside Flex container):**
![Screenshot from 2022-04-28 03-59-13](https://user-images.githubusercontent.com/85633460/165706831-fb63216e-865e-4020-a7a8-8eb38842a783.png)

**How BS fix this problem for [its icons](https://icons.getbootstrap.com/icons/cart-fill/) inside the components:**
```
.bi {
  display: inline-block;
  vertical-align: -.125em;
}
```

**For hummingbird (material icons) can be:**
```
.material-icons {
  font-size: 150%;
  vertical-align: -0.25em; 
}
```
_em is relative to the font-size of its direct or nearest parent._
![bs](https://user-images.githubusercontent.com/85633460/165707705-14248175-c154-4a08-9f08-279cbfc55b0e.png)

**Another example:**
Cart icon is a flex item so icon is aligned vertically.
User icon is NOT a flex item so `vertical-align: middle;` will be used for it, but it's not vertically aligned.
![Screenshot from 2022-04-28 04-50-48](https://user-images.githubusercontent.com/85633460/165715202-8ff44dad-6a31-4ed8-ba41-186d61698a64.png)

Fixed by `vertical-align: -0.25em;`
![Screenshot from 2022-04-28 04-52-32](https://user-images.githubusercontent.com/85633460/165715562-fda7e718-1eb4-4b28-8e85-134668841ecb.png)

**Comment by SharakPL** [comment]
> Fixed by `vertical-align: -0.25em;`

IMO never a good idea. If you change the font-size of the label it will be misaligned again. Best way to do it responsively is:
```css
.any-button-with-icon {
  display: flex;
  flex-flow: row nowrap;
  align-items: center;
  gap: .5rem;
}
```

**Comment by NeOMakinG** [comment]
> > Fixed by `vertical-align: -0.25em;`
> 
> IMO never a good idea. If you change the font-size of the label it will be misaligned again. Best way to do it responsively is:
> 
> ```css
> .any-button-with-icon {
>   display: flex;
>   flex-flow: row nowrap;
>   align-items: center;
>   gap: .5rem;
> }
> ```

Yeah this was the thing I was thinking about, we could add this to the `.btn-with-icon` helper class

**Comment by mparvazi** [comment]
@SharakPL @NeOMakinG 

I think in the future all of the components will be flex-item, so we wont have any problem about icon alignment.

But currently we need a **fallback** for icons that are not flex-item.
This rule `vertical-align: -0.25em; ` only impacts icons with `display: block;`

![Screenshot from 2022-04-28 04-50-48](https://user-images.githubusercontent.com/85633460/165741830-6fc537c7-a4af-4707-b65b-a8e0b07057c9.png)
Cart icon has `display: flex;`
User icon has `display: block;` (so it's not aligned vertically)

**Comment by SharakPL** [comment]
Then best fallback is `vertical-align: middle`. The reason for misalignment is very often the iconfont itself.

**Comment by mparvazi** [comment]
`vertical-align: middle` already is inside `.material-icons {}` but not works and have bug in BS.

**Comment by Hlavtox** [comment]
I always use flex for aligning this, but a small downside (in some cases) is, that the text will not wrap 'under' the icon.

**Comment by SharakPL** [comment]
If you want to wrap then don't use flex. Just `float: left` on the icon.
