### ISSUE TITLE
Optimize bundles sizes, add csso, fix lighthouse issues

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/hummingbird#252]

**Comment by Hlavtox** [comment]
We need to divide the assets per-module again, so they are not loaded in the bundle if not needed.

**Comment by NeOMakinG** [comment]
> We need to divide the assets per-module again, so they are not loaded in the bundle if not needed.

Seems impossible in the current state of PrestaShop

**Comment by Hlavtox** [comment]
Yes, but at least the module CSS will be loaded only on pages where it's needed, not everywhere.

**Comment by Hlavtox** [comment]
With the way hummingbird is written now, all JS, all CSS, for all modules (even uninstalled) are loaded absolutely everywhere.

**Comment by NeOMakinG** [comment]
> With the way hummingbird is written now, all JS, all CSS, for all modules (even uninstalled) are loaded absolutely everywhere.

Yeah I know, we can improve it and it's almost ready: https://github.com/NeOMakinG/theme-refacto/commit/d570e8b09f0147bfe9fbf35d0b26372fe8373fe2

But we can't do it perfectly for sure :(

**Comment by NeOMakinG** [comment]
@Oksydan wants to take this subject, I'll move it to WIP

**Comment by Oksydan** [comment]
Assign me 👀
