### ISSUE TITLE
Verify the compatibility with every natives modules

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/hummingbird#255]
It would be also interesting to test PSX and some community modules, they should works as we didn't change that much hooks placements and blocks, but some will break because they depends on bootstrap 4/alpha

**Comment by alfonsolr09** [comment]
I think the most important thing is that the theme is compatible with native modules, then each developer must update their modules to make them compatible.

**Comment by JBLach** [comment]
I have created a list of modules to check to know what progress we have on this issue. I'll take care of that too.

- [ ] blockreassurance
- [ ] blockwishlist
- [ ] contactform
- [ ] productcomments
- [ ] ps_banner
- [ ] ps_bestsellers
- [ ] ps_brandlist
- [ ] ps_categorytree
- [ ] ps_checkpayment
- [ ] ps_contactinfo
- [ ] ps_crossselling
- [ ] ps_currencyselector
- [ ] ps_customeraccountlinks
- [ ] ps_customersignin
- [ ] ps_customtext
- [ ] ps_dataprivacy
- [ ] ps_emailalerts
- [ ] ps_emailsubscription
- [ ] ps_facetedsearch
- [ ] ps_featuredproducts
- [ ] ps_imageslider
- [ ] ps_languageselector
- [ ] ps_linklist
- [ ] ps_mainmenu
- [ ] ps_newproducts
- [ ] ps_searchbar
- [ ] ps_sharebuttons
- [ ] ps_shoppingcart
- [ ] ps_socialfollow
- [ ] ps_specials
- [ ] ps_supplierlist
- [ ] ps_viewedproduct
- [ ] ps_wirepayment
- [ ] psgdpr

**Comment by NeOMakinG** [comment]
> I have created a list of modules to check to know what progress we have on this issue. I'll take care of that too.
> 
> * [ ]  blockreassurance
> * [ ]  blockwishlist
> * [ ]  contactform
> * [ ]  productcomments
> * [ ]  ps_banner
> * [ ]  ps_bestsellers
> * [ ]  ps_brandlist
> * [ ]  ps_categorytree
> * [ ]  ps_checkpayment
> * [ ]  ps_contactinfo
> * [ ]  ps_crossselling
> * [ ]  ps_currencyselector
> * [ ]  ps_customeraccountlinks
> * [ ]  ps_customersignin
> * [ ]  ps_customtext
> * [ ]  ps_dataprivacy
> * [ ]  ps_emailalerts
> * [ ]  ps_emailsubscription
> * [ ]  ps_facetedsearch
> * [ ]  ps_featuredproducts
> * [ ]  ps_imageslider
> * [ ]  ps_languageselector
> * [ ]  ps_linklist
> * [ ]  ps_mainmenu
> * [ ]  ps_newproducts
> * [ ]  ps_searchbar
> * [ ]  ps_sharebuttons
> * [ ]  ps_shoppingcart
> * [ ]  ps_socialfollow
> * [ ]  ps_specials
> * [ ]  ps_supplierlist
> * [ ]  ps_viewedproduct
> * [ ]  ps_wirepayment
> * [ ]  psgdpr

Well, when I look at this list, I feel like this is going to be a lot of work too, as usually, if you need anything, ping me 🙏

**Comment by NeOMakinG** [comment]
@JBLach Even if it's not merged, `ps_brandlist` and `ps_supplierslist` will be compatible with your PR right? 

We can check them then, I checked `blockwishlist` as I just opened the PR to make it compatible 

What about `ps_emailalerts` then?

**Comment by JBLach** [comment]
@NeOMakinG yes these modules are compatible and works fine, I thought that we don't support boostrap 5 in override, but everything is fine, and my changes mainly change the style

**Comment by NeOMakinG** [comment]
@JBLach I just checked every modules then, let's close the issue when both PRs are merged :)
