### ISSUE TITLE
Categories with subcategories on category page are wrongly displayed

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/hummingbird#256]
![image](https://user-images.githubusercontent.com/14963751/166239927-b84f856e-ffca-4513-a2d4-1d0233c47138.png)

We should probably add a proper collapse there, we definitely can't show every categories by default because some big websites won't agree with that choice, but it should be easily adaptable

**Comment by Hlavtox** [comment]
We should add an option to the the module called "Open the current category". ;-)

**Comment by SharakPL** [comment]
How about using 1 chevron arrow and just rotating it 180deg instead of showing/hiding + and -?

**Comment by mparvazi** [comment]
With chevron it will be as same as faceted search UI.

**Comment by NeOMakinG** [comment]
> With chevron it will be as same as faceted search UI.

and it looks pretty fine to me, but this is obviously something that the product team will notice while reviewing
