### ISSUE TITLE
Order confirmation font size is buggy

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/hummingbird#257]
![image](https://user-images.githubusercontent.com/14963751/166240570-7b8b55f7-9e13-44dd-b0c7-9039de4569ba.png)

Probably related to
https://github.com/PrestaShop/hummingbird/pull/243

**Comment by mparvazi** [comment]
I'm ready to work on it.

**Comment by mparvazi** [comment]
![Screenshot from 2022-05-09 10-58-47](https://user-images.githubusercontent.com/85633460/167438276-efd93734-235f-4dff-92e6-bb626e7914c9.png)
