### ISSUE TITLE
Handle cart errors better

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/hummingbird#267]
If something goes wrong during adding product to cart, empty modal is displayed.

We should get inspired by @Oksydan's theme and handle these situations better. ;-)

https://github.com/Oksydan/is_shoppingcart

**Comment by Oksydan** [comment]
I can make a PR

**Comment by Oksydan** [comment]
Actually I think we should modify core a bit.
Add to cart action should return modal inside response.
We could create actionHook that we should pass product added to cart. 
Module will register to that hook and will be able to append content to response.
In FO we will be able to listen to updateCart with reason (addToCart) and check if that response.MODULE_NAME.whatever exist and for example append it to body and trigger modal.show. We are able to pass data via module with just json format (good for tracking datalayer for example) or for example toast.
What you think @NeOMakinG

**Comment by Hlavtox** [comment]
Let's see what Valentin has to say, but for me the current system, if it works is OK, or at least you in your theme handled it fine.

**But if you want to improve the functionality, for me:**
- It should support both modal and toast. I have a client that just wants to have a small toast notification on right top.
- It should support also users who want to have a cart sidebar on the right or a dropdown on right top, like you do in your theme.
- If any error happens on cart actions, it should be presented to the user in a clear way.

**And regarding this topic generally, I would like this to be in v8:**
- We should provide a commented out, but working product-list add to cart functionality https://github.com/PrestaShop/PrestaShop/issues/23496
- We need to fix this bug - https://github.com/PrestaShop/PrestaShop/issues/23187

Ping @mparvazi @kpodemski

**Comment by NeOMakinG** [comment]
> Actually I think we should modify core a bit. Add to cart action should return modal inside response. We could create actionHook that we should pass product added to cart. Module will register to that hook and will be able to append content to response. In FO we will be able to listen to updateCart with reason (addToCart) and check if that response.MODULE_NAME.whatever exist and for example append it to body and trigger modal.show. We are able to pass data via module with just json format (good for tracking datalayer for example) or for example toast. What you think @NeOMakinG

If you feel like it's a good idea and improve the way we handle the add to cart action, go for it, but first you need to create an issue on the core side, it needs to be validated by the product team, and then we can implement it

Also, keep in mind that Hummingbird should be compatible with the 1.7.8.x version, meaning that we have to handle it in both ways, that's the deal!

**Comment by mparvazi** [comment]
@Hlavtox 
About the second issue: https://github.com/PrestaShop/PrestaShop/issues/23187
As you know it should be fixed on Core, but in hummingbird at least there is a warning toast:

https://user-images.githubusercontent.com/85633460/167361325-f50d8c91-3a04-4fec-a4a0-c7c12a40dfd4.mp4

The weird thing in this situation is the json response:
There is an error, but success is true and new value for quantity confirmed!

![Screenshot from 2022-05-09 03-32-26](https://user-images.githubusercontent.com/85633460/167361811-c6408174-f7bf-4112-9ed6-eb2dfba591b1.png)

**Comment by Hlavtox** [comment]
@mparvazi Can you also check on the product page? 🚀 Please 🙏

- If you click slowly and wait until refresh, the add to cart goes grey and it wont allow you to add it.
- But if you click plus quickly and immediately press add to cart, does it show empty modal or the nice toast?

**Comment by NeOMakinG** [comment]
> @mparvazi Can you also check on the product page? 🚀 Please 🙏
> 
> **Current behavior on classic and classic rocket:**
> 
> * If you click slowly and wait until refresh, the add to cart goes grey and it wont allow you to add it.
> * But if you click plus quickly and immediately press add to cart, does it show empty modal or the nice toast?

What about disabling the `add-to-cart` button right after any quantity actions, until we have a response?

**Comment by mparvazi** [comment]
IMO we don't need to spy on quantity input for this problem (as it done for classic-theme)

My suggestion:
1- `PS/themes/_core/js/cart.js`

_These changes does not impact classic-theme_

![Screenshot from 2022-05-09 06-56-13](https://user-images.githubusercontent.com/85633460/167398470-e6d1b41c-3a3c-4da8-8835-41b6376f1ca3.png)

2- Then in hummingbird:

![Screenshot from 2022-05-09 07-11-18](https://user-images.githubusercontent.com/85633460/167398589-065fb64d-5e61-4d9b-9923-da33e48e6126.png)


https://user-images.githubusercontent.com/85633460/167399434-ff8bac5f-9bbe-4345-8f85-f5d4b95916a7.mp4

**Comment by mparvazi** [comment]
@NeOMakinG 

Will be fixed here (Line 433):
https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/front/CartController.php

With these changes:

![170018121-2b1ebf70-3197-4690-94ed-f38fb60dd563](https://user-images.githubusercontent.com/85633460/177358849-1fa5d844-94ef-4b15-8c6c-4c36a2f78272.png)


After that we won't have something like this (success is true but response has errors):

![169844350-886889af-8bda-4437-beaa-c142eb3b826f](https://user-images.githubusercontent.com/85633460/177359082-27e0b04e-c730-4183-b111-5ab5eebf608c.png)

So on error response will be:

![169845143-8cf755f7-81ae-49ea-b548-657278942e09](https://user-images.githubusercontent.com/85633460/177359333-ce0d1b82-0964-4e16-801c-43224de69b2f.png)

Btw I didn't start any PR for that, you know it's about the Core!

**Comment by NeOMakinG** [comment]
@mparvazi did you create a PR on the core? Can you link it there?

Does it require some tweaks inside the theme? Or we can just close this issue?

**Comment by mparvazi** [comment]
@NeOMakinG 

Ok, I'll make a PR there.
Inside the theme we need to add error handler for add to cart action (it's easy).
So you can close this issue.
