### ISSUE TITLE
[BUG] In page 404 we have two search inputs with same ID

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/hummingbird#273]
It will cause an error on `src/js/responsive-toggler.ts`:
The search input will be hidden on mobile viewport for page 404.

![Screenshot from 2022-05-08 06-03-48](https://user-images.githubusercontent.com/85633460/167291363-72f400c5-d533-4aae-95d4-2aedfc4aad12.png)

**Comment by Hlavtox** [comment]
The _desktop_search id should be used ONLY in the header - single time. We should put it outside the search TPL to the header directly.

**Comment by NeOMakinG** [comment]
I'll take this, quick one! Thanks for the issue 👍

**Comment by NeOMakinG** [comment]
If anyone from the community wants to take it, feel free, really easy!

**Comment by mparvazi** [comment]
This error will be happen everywhere you use `{hook h='displaySearch'}`

**Comment by mparvazi** [comment]
![Screenshot 2022-05-10 at 15-23-49 404 error](https://user-images.githubusercontent.com/85633460/167706552-8e2b11b0-3ebc-4bd9-9fbb-f1ac3c687f9c.png)

**Comment by NeOMakinG** [comment]
> ![Screenshot 2022-05-10 at 15-23-49 404 error](https://user-images.githubusercontent.com/85633460/167706552-8e2b11b0-3ebc-4bd9-9fbb-f1ac3c687f9c.png)

Looks awesome, did you test the product not found version? I know both template are pretty linked

**Comment by mparvazi** [comment]
Ok, I'll take a look at it later.

**Comment by NeOMakinG** [comment]
We did miss it but it's been fixed already 😄
