### ISSUE TITLE
Move every selectors to the theme side instead of the `prestashop` object

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/hummingbird#274]
Every selectors from the theme should be exported by webpack to `window.Theme.selectors` instead of `window.prestashop.themeSelectors`

We decided to split the theme components and whatever from the core, in order to make it clearer, everything exported from `theme.ts` is naturally usable inside `window.Theme`, we can export a `selectors` object from `theme.ts` and use it everywhere in our codebase instead of `window.prestashop`

**Comment by MeKeyCool** [comment]
I am on this one ^^
