### ISSUE TITLE
How to exclude Your account and Store information?

### ISSUE THREAD

**Issue by bastijan** [PrestaShop/hummingbird#286]
How to exclude Your account and Store information from the footer?

It's frustrating that those elements show on a page without any markup in the template!!!

**Comment by Hlavtox** [comment]
Just disable the two modules and the blocks will be hidden. ;)

**Comment by bastijan** [comment]
This is not the solution in teamwork. I need a solution in code.
We are working in team all is in docker and I cant expect from other team members to repeat manually something in back office.

**Comment by kpodemski** [comment]
@bastijan you can control enabled modules on the `theme.yml` level

https://devdocs.prestashop.com/1.7/themes/getting-started/theme-yml/

**Comment by kpodemski** [comment]
Oh, and btw. This project is still a work in progress. It isn't stable yet.

> We are working in team all is in docker and I cant expect from other team members to repeat manually something in back office.

That would be hard without additional scripts/tools for your team. Even if you change something in the theme.yml other devs have to reset the theme settings.

**Comment by bastijan** [comment]
@kpodemski that is a point.
Theme Hummingbird, in theme.yaml I tried to_disable - doesn't work

```
    to_disable:
      - ps_linklist
```

I removed ps_linklist from 

```
  hooks:
    modules_to_hook:
```
    
but this also doesn't work.    

Something is wrong with theme.yaml parsing...

Is it possible to override module call without disabling it?

**Comment by kpodemski** [comment]
@bastijan 

have you tried to reset your theme?

with developer mode enabled you can go to "Design -> Themes" and click "Reset theme to the default settings"

**Comment by NeOMakinG** [comment]
@bastijan when you change the `theme.yml` file, you will probably need to remove/reset the related json from `config/themes/yourthemename`

**Comment by bastijan** [comment]
@NeOMakinG deleting related json works. But this is strange, json should be updated on each theme config changes or theme activation.
