### ISSUE TITLE
How to exclude Your account and Store information PROGRAMMATICALLY ?

### ISSUE THREAD

**Issue by bastijan** [PrestaShop/hummingbird#287]
How to exclude Your account and Store information from the footer?

It's frustrating that those elements show on a page without any markup in the template!!!

@Hlavtox wrote "Just disable the two modules and the blocks will be hidden. ;)" but this is not a solution in a teamwork environment.

Sorry @Hlavox but you are not funny.

I need a solution in code.
We are working in the team all is in docker and I can't expect other team members to repeat something manually in the back office.

**Comment by kpodemski** [comment]
Please do not duplicate issues.

**Comment by mparvazi** [comment]
@bastijan 

@Hlavtox said that because you didn't provide enough information.
That solution was not for fun!

You can check PS docs for it (theme.yml).

**Comment by NeOMakinG** [comment]
Replied to your first issue, you probably have to clear some files after changing the `.yml`

**Comment by Hlavtox** [comment]
First of all - I got you a legitimate answer to find where this code is coming from. If you don't specify what you want, cry and use exclamation marks, you won't get good answers. 👍

Now when we know what you want - I think you must reinstall the theme to apply the changes in the yml, there is some weird cache somewhere.

```
if (Module::isInstalled('my_module')) {
$module = Module::getInstanceByName('my_module');
$module->uninstall();
```
