### ISSUE TITLE
[RESPONSIVE - My account Page] Credit slips

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/hummingbird#29]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2
Desktop's issue: https://github.com/PrestaShop/theme-refacto/issues/23

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=298%3A11931)

#### UX and design explanations
- The header text in the first column is differentiated from the second column text by a heavier weight. It makes the header easy to read with its contrast.

#### Mockups

Credit slips
![responsive - credit slips](https://user-images.githubusercontent.com/54888056/138280108-0d911d93-5669-4e11-b3d6-ae91d582783d.png)

Empty credit slips
![responsive - empty credit slips](https://user-images.githubusercontent.com/54888056/138279742-aa6f7456-4c63-4271-b70a-3d3fadad8259.png)

**Comment by SharakPL** [comment]
Could someone explain what the heck does credit slip even mean? What generates it? Polish translation for it is meaningless. It looks like something used only in some countries, like Checks module. Maybe it should be disabled by default or at least provide an option to disable it.

**Comment by adamus007p** [comment]
A credit slip is the same as a credit note.
[US]

A credit note is a piece of paper that a shop gives you when you return goods that you have bought from it. It states that you are entitled to take goods of the same value without paying for them.
[British]


What it the main English language version in Prestashop ( US or British) ?

I used to see more credit note then credit slip (US).

In Polish:
Nota kredytowa, inaczej nota uznaniowa (ang. credit note) – pisemny dokument wystawiony przez wierzyciela informujący dłużnika o umorzeniu określonej należności. Przykładem jest wystawienie noty kredytowej przez dostawcę dla nabywcy jeżeli nastąpił błąd w fakturze, zwrot towarów lub ich uszkodzenie.
https://pl.wikipedia.org/wiki/Nota_kredytowa

**Comment by SharakPL** [comment]
Then why is it called _Credit slips_ and not _Refunds_ or _Returns_. Even Google doesn't know what credit slip really is 😂

**Comment by NeOMakinG** [comment]
![image](https://user-images.githubusercontent.com/14963751/153233765-8986b6d5-3f43-41f2-88dc-27c004993c06.png)

Looks like googe knows, this is the right name, we could have use Credit Note too

Because it's not a refund, it's a receipt of that refund

Anyway, ping @PrestaShop/product-team, see the discussion, if you think we should change this naming, just tell us

**Comment by adamus007p** [comment]
I see that this is completely different translation in Polish.
Credit note - faktura korygująca and possible in different countries too.


Anyway in that links in EU there is a term credit note, not credit slip.

But in Polish it can be other meaning for this.

Beside that  I know Prestashop keep very weird and old things and names like order states which make a mess.


https://poradnikprzedsiebiorcy.pl/-credit-note-w-wnt-co-to-jest-i-jak-zaksiegowac-note-kredytowa

https://poradnikprzedsiebiorcy.pl/-credit-note-w-wnt-co-to-jest-i-jak-zaksiegowac-note-kredytowa

https://poradnikprzedsiebiorcy.pl/-faktura-korygujaca-a-nota-podstawowe-roznice

https://www.infakt.pl/blog/faktura-korygujaca-nota-korygujaca-jaka-roznica/


What it the main English language version in Prestashop ( US or British) ?

**Comment by SharakPL** [comment]
> Because it's not a refund, it's a receipt of that refund
> 

You need to make a return:
1. print a return form,
2. fill it up and send back with all returned products

to get a refund:
3. money returned
4. invoice correction generated

and have credit note generated - still no idea what it's for, other than just a database record to have this return listed on my account... or is it the same as invoice correction?
___

Anyway seems to me _credit slip_ is only the final step of whole process, so IMO it should be called __Returns__ because that's the main theme here.

`$my_account_urls` has 4 items by default:
- Personal information
- Orders
- Credit slips (polish default translation is _Moje pokwitowania - korekty płatności_ which translates back to _My receipts - payment corrections_ - you see why it's so confusing)
- Addresses

Nothing about __Returns__ specifically!
___
**customeraccount** module uses this frase: `Credit slips you have received after canceled orders.` So is it also about partial returns or just complete order cancelation?

**Comment by MatShir** [comment]
There are definitely some wordings improvements, we can do here :) 
Thanks for bringing up the issue. We can also use credit note, or credit memo. 
We need to be careful if we change it, we will need to change the doc and wording into the software, many places where this issue is used :)

**Comment by adamus007p** [comment]
@SharakPL I need to install new presta and check it.

@SharakPL you mean change this name when customer is logged in?

If you meant that you are right. For non-business customer I believe credit note say nothing. Returns would be better and inside it it could you naming about credit notes.
At least customer would know what could be expect inside.

**Comment by SharakPL** [comment]
> I was asking about English :P You can choose English during installation, so what it the default version?

English | English | en - flag of USA
English GB | English | gb - flag of GB

Most of the time I only use english as a 2nd language, but I'd rather use **en with GB flag**

**Comment by kpodemski** [comment]
@SharakPL 

Credit slip is  "potwierdzenie zwrotu".

You can read more about it here:
https://doc.prestashop.com/pages/viewpage.action?pageId=29656382

It's not about invoicing, it's just a confirmation to the customer that products have been returned.

**Comment by SharakPL** [comment]
Thanks @kpodemski 

> Credit slip is "potwierdzenie zwrotu".
> 
So "Return confirmations" then. IMO **"Returns"** (PL: "Zwroty") is enough for clients to know what this page is about :)

**Comment by MatShir** [comment]
Let's not forget that the theme of the project is meant to be a generic theme. Depending on the business and the size of the shop, the uses can change. But it is true that a separate credit slip on the interface, which is itself connected to an order, is not necessarily the best UI to do. We copied the behavior from the classic theme, but maybe it is time to improve it. Are you feedback from merchant? @prestascott perhaps we can have at some good ecommerce practices to find a quick win optimization ?

**Comment by SharakPL** [comment]
So it's an invoice correction then. Basically another invoice for the order, just stating what on the original invoice changed: old record and new record. What if there was no invoice for the order, like when invoices are disabled? Should it still generate an invoice correction?

**Comment by MatShir** [comment]
In theory, when the invoice is sent to client. If you want to do a correction, you should send a credit note for major changes in the invoices.

**Comment by adamus007p** [comment]
@MatShir I am writing from merchant and customer perspective. Maybe I am wrong, but there no sense to keep only credit notes separate from order. It could be together with order in history. This is a part of whole order process and everything could be in one place.

Is there any reason that it is separated?

**Comment by MatShir** [comment]
No particular reason, maybe just an old school layout 🤷

**Comment by SharakPL** [comment]
OK, so here's how it works in PL. If there's a mistake on the invoice (wrong VAT number, wrong address, etc.) or there was a change in value (change of price, added discount, partial or complete return, etc.) the seller have to make **correction invoice** that buyer has to sign and send back (not always necessary).
**Correction note** (or as you call it _credit slip_) can be made **only by the buyer** and it only handles simple mistakes, like address, product names, etc. If there's a change in invoice value, so also for every partial or complete return, then **correction invoice** has to be created by the seller.

I guess this is one of the features that are very hard to setup for every country separately. Like Prestashop's B2B mode works only in France and maybe few other countries with similar configuration.

**Comment by MatShir** [comment]
> OK, so here's how it works in PL. If there's a mistake on the invoice (wrong VAT number, wrong address, etc.) or there was a change in value (change of price, added discount, partial or complete return, etc.) the seller have to make correction invoice that buyer has to sign and send back (not always necessary).

This part is the same in France. This feature is missing in PrestaShop because the new invoice (correction invoice) need to be "linked" to the first one, saying it is a correction of the first invoice.

**Comment by NeOMakinG** [comment]
I guess this is done, if there are some things to polish, let's see this after product review

I'll create another dedicated issue about wording
