### ISSUE TITLE
Different display for quickview on touch screen

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/hummingbird#291]
In screens that hover not works, need to show quickview button in product box.
```scss
// hide quickview touch button

@media (hover: none) and (pointer: coarse) {
  // hide hover quickview box
  // show quickview touch button
}
```

https://user-images.githubusercontent.com/85633460/169580931-bf914e64-b7d7-4445-a358-47909cde0766.mp4

**Comment by eshraw** [comment]
Thanks for the suggestion @mparvazi, I think it's a neat idea !
LGTM @NeOMakinG
