### ISSUE TITLE
[DESKTOP - Product Page] Image and slider

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/hummingbird#3]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2
Responsive's issue: https://github.com/PrestaShop/theme-refacto/issues/4

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=119%3A7299)

#### UX explanations
- Layout changes and image thumbnails are now placed on the left side of the main image to save space from scrolling
- The selected image is still visually indicated by a purple outline to let customers know which image is selected
- Horizontal Scroll 

#### Mockup
![image and slider](https://user-images.githubusercontent.com/54888056/135485503-a9e398a3-1a62-4245-9795-2b76f8e493a8.png)

**Comment by eveneme** [comment]
I guess the border-radius should be similar.
