### ISSUE TITLE
Product details shows detail that can confuse customers

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/hummingbird#305]
![imagen](https://user-images.githubusercontent.com/10741347/171025016-fcd6b104-7214-4944-92ff-2b5245aeb257.png)
this detail is the hook `actionProductOutOfStock` but the product has stock. Some customers can misunderstand this and think there is no stock

**Comment by rodriciru** [comment]
I'm a little confused.
I see that action hooks only executes actions, no display nothing.
But devdocs say this:

> actionProductOutOfStock
>     This hook displays new action buttons if a product is out of stock 

So it displays something or not?. If not, I think it shouldn't be any li.details and only the hook outside the accordion

**Comment by NeOMakinG** [comment]
I guess we could remove it in favor of product ability 

https://github.com/PrestaShop/PrestaShop/pull/25062
