### ISSUE TITLE
Should we add customer modules to signing?

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/hummingbird#311]
In my store I installed wishlist and email alerts module, which add some divs to my account menu, but I'm thinking of adding to the dropdown menu in header.
But I don't know how to do that.
I add a displayCustomerAccount hook, but this adds the markup for the my account block, so it won't fit.
And I don't have any ideas left.
So, it's possible?

**Comment by Hlavtox** [comment]
Yes, this is a problem - I made an issue for this https://github.com/PrestaShop/PrestaShop/issues/26849.
You can try to ping the dev team for this.

**Comment by NeOMakinG** [comment]
Cleaning up things, this is related to the core/module, can't and shouldn't be managed by the theme itself atm, let's continue the discussion on the original issue @Hlavtox linked
