### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by adamus007p** [PrestaShop/hummingbird#328]
Hello guys, is there any ETA for beta version?

**Comment by NeOMakinG** [comment]
> Hello guys, is there any ETA for beta version?

Hello @adamus007p, thanks for the interest!

There is no ETA yet, as the project is not prioritized, we're still trying to work on it as much as possible but we can't decide on a date.

The good news is that the project is in a good state, I would bet on some month if I'm able to unblock some time for it :)

PS: I'm closing the issue to avoid polluting the repository, feel free to continue to discuss on it!
