### ISSUE TITLE
Viewport check: 320px

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/hummingbird#340]
## Header logo
The logo container display must be defined as block, in current implementation there is overlap with search icon if the logo width is more than 150px.

![logo](https://user-images.githubusercontent.com/85633460/177984701-d550c855-d78c-42bd-ba8c-84f8865ed63a.png)

## User menu button (Fixed by #343)
When customer is not logged-in there is an unwanted right padding, so we have extra space on the right side.

![user](https://user-images.githubusercontent.com/85633460/177984976-45425e70-d12b-4fca-8861-c0a1a90f9f97.png)

## Newsletter block
Need to use full-width style for input elements.

![newsletter](https://user-images.githubusercontent.com/85633460/177985175-f3a5d562-3bd9-4e77-9d88-ac210a9860e8.png)

## Pagination
We have overflow when Next and Previous buttons are displayed at the same time. I think we need to hide text label for mobile screen.

![pagination](https://user-images.githubusercontent.com/85633460/177985378-75f92bcb-4b45-40bd-ac26-d17aeb2541c1.png)

 ## Account page (Fixed by #357)
It's better to use an unstyle button for Back and place it under the page title.

![back](https://user-images.githubusercontent.com/85633460/177985595-afe1c645-68f4-4af6-9173-1a316c4d5ca9.png)

## Products list
Just a suggestion: showing one product per column on mobile screen.

![products](https://user-images.githubusercontent.com/85633460/177985636-95c6248a-5e5c-42dc-a6c4-9ce08e6cdbb5.png)

**Comment by mparvazi** [comment]
I tried to change Pagination display for XS screen. Not bad if page numbers aren't too much:

![Screenshot from 2022-07-08 23-38-35](https://user-images.githubusercontent.com/85633460/178055757-7f4eaf94-8d56-4f21-9f34-c957eef24da7.png)

But what about this?!

![Screenshot from 2022-07-08 23-35-16](https://user-images.githubusercontent.com/85633460/178055706-17ff076b-3f61-4d1a-90ad-51af0062afcd.png)

**Comment by mparvazi** [comment]
Wdyt about this?
A compact version for XS screen:

![Screenshot from 2022-07-09 00-11-10](https://user-images.githubusercontent.com/85633460/178059786-5ad8eb2e-a293-4b30-9454-af1a394beb0d.png)

Support page numbers until 999 :P

**Comment by mparvazi** [comment]
I used pagination like this for ps 1.6 theme and it works fine:

![Screenshot 2022-07-10 113428](https://user-images.githubusercontent.com/85633460/178134836-9cb1e8c5-2bfd-4b81-8a8d-abc7cb808fac.png)


![Screenshot 2022-07-10 113340](https://user-images.githubusercontent.com/85633460/178134841-d0081917-505d-4abe-bbbc-31af9cdffea1.png)

**Comment by SharakPL** [comment]
I like that last one!
The compact one begs a question:
![obraz](https://user-images.githubusercontent.com/5007456/178153452-bdb460b7-dc11-4efa-bbfa-66b5c645efb3.png)
Does it go to previous page or to 1st?

**Comment by SharakPL** [comment]
Previous/next buttons are obsolete if it would look like this:
![obraz](https://user-images.githubusercontent.com/5007456/178153562-37014f19-48ed-46b6-ba08-1e58c7f91a77.png)

**Comment by Hlavtox** [comment]
Yeah, the prev/next ones maybe can go on mobile, or we can put them to next line, that also looks good.

**Comment by mparvazi** [comment]
Can we decrease page numbers on left and right side of selected page? (for mobile by css tricks)
![178153562-37014f19-48ed-46b6-ba08-1e58c7f91a77](https://user-images.githubusercontent.com/85633460/178157964-589d537e-02f8-491d-9ab8-2f28c7504fec.png)

I mean change it to:
`< 11 | 7 (6) 5 | 1 >`

**Comment by SharakPL** [comment]
Imo the top version is better since < and > are just duplications for 7 and 5 in this case. Top one gives more options to the user without taking more space.

**Comment by mparvazi** [comment]
@NeOMakinG Wdyt?

Desktop, tablet:

![178134836-9cb1e8c5-2bfd-4b81-8a8d-abc7cb808fac_2](https://user-images.githubusercontent.com/85633460/178458475-509ea1de-621e-403f-b9a8-ae35188c517b.png)

or 

![178134836-9cb1e8c5-2bfd-4b81-8a8d-abc7cb808fac](https://user-images.githubusercontent.com/85633460/178457042-217000bc-1c1b-4ae0-a0d3-84c96155d45e.png)

Mobile:

![178134841-d0081917-505d-4abe-bbbc-31af9cdffea1](https://user-images.githubusercontent.com/85633460/178457065-144c2bdb-8e9c-4b9c-998a-71105990ec99.png)

**Comment by NeOMakinG** [comment]
@TristanLDD can we have your input on this?

**Comment by SharakPL** [comment]
> > Imo the top version is better since < and > are just duplications for 7 and 5 in this case. Top one gives more options to the user without taking more space.
> 
> I guess it's not about duplication but make it more accessible with your finders, it's easier to click on a <> button than on a number on mobile

Actually it's all the same :) and if it's about having < and > in the mix then maybe we should use the most obvious: 

| « | ‹ | 6 | › | » |

**Comment by NeOMakinG** [comment]
Go for the most obvious one anyway, if the product or design team wants to set some feedback later, they'll do it, 100% trusting both of you on this subject ;)

**Comment by mparvazi** [comment]
Fix for logo block.
Wdyt?

## Before
https://user-images.githubusercontent.com/85633460/180173360-a6f1cee6-b39e-4b56-84fb-7b99f5384364.mp4

## After
https://user-images.githubusercontent.com/85633460/180173470-f79d877d-f156-413e-905b-ac79d6095e94.mp4

**Comment by NeOMakinG** [comment]
> 

Looks fine to me, I don't see any blockers!

**Comment by JBLach** [comment]
I will improve the view of the newsletter.

**Comment by JBLach** [comment]
> I will improve the view of the newsletter.

Oh now I see that the newsletter  has already been corrected and it looks good

**Comment by NeOMakinG** [comment]
> > I will improve the view of the newsletter.
> 
> Oh now I see that the newsletter has already been corrected and it looks good

Oh, I don't even remember who did this but that's cool then!
