### ISSUE TITLE
Add to cart in product list

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/hummingbird#347]
SPECS: https://github.com/PrestaShop/PrestaShop/issues/23496

I think it would be good to finally implement proper product list adding to cart.

**Add this to product miniature:**
```
{if $product.add_to_cart_url}
<form action="{$urls.pages.cart}" method="post">
    <input type="hidden" value="{$product.id_product}" name="id_product">
    <input type="hidden" name="token" value="{$static_token}" />
    <input type="number" name="qty" value="1" onclick="return false;">
    <button data-button-action="add-to-cart">Buy</button>
</form>
{/if}
```

**Product**
- Make a product.
- Disable ordering out of stock.
- Set quantity of this product to 2.

**Adding to cart**
- Add two pieces of the product to cart from the product list.
- The button now should go disabled.

**Changing quantity**
- Change quantity input to 3, add to cart button should go disabled. Or it should revert back to 2.

**We need to fix this fast clicking bug in Hummingbird**
https://github.com/PrestaShop/PrestaShop/issues/23187

**Comment by mparvazi** [comment]
@Hlavtox 

I think this PR will be solved the fast click problems and out of stock products add to cart management:
https://github.com/PrestaShop/PrestaShop/pull/29016

Then just need to create something like `cart.ts` to manage response from back-end: 
1. enable/disable add-to-cart button and waiting spinners until response comes from back-end
2. handle cart errors (toast, alert)
