### ISSUE TITLE
Undefined index: additional_description in PS 1.7.x versions

### ISSUE THREAD

**Issue by lramos-prolaser** [PrestaShop/hummingbird#367]
I'm testing Hummingbird in a 1.7.8.7 PrestaShop version and I found an `Undefined index` issue with `additional_description` field in `category-footer.tpl` . 

Problem is that this field was added in PrestaShop 8 (https://github.com/PrestaShop/PrestaShop/pull/27292) and does not exists in 1.7.x versions. 

To fix it, just add an isset() to check if this field is available:
```
<div id="js-product-list-footer">
    {if isset($category.additional_description)}
      {if $category.additional_description && $listing.pagination.items_shown_from == 1}
        {$category.additional_description nofilter}
      {/if}
    {/if}
</div>
```

**Comment by Hlavtox** [comment]
We can do this:
`{if !empty($category.additional_description) && $listing.pagination.items_shown_from == 1}
`
This should check for both isset and not empty. @NeOMakinG

**Comment by NeOMakinG** [comment]
Agree with @Hlavtox 

If you want to contribute to it, don't hesitate @lramos-prolaser 👍
