### ISSUE TITLE
Product page, size change, availability not updating on page

### ISSUE THREAD

**Issue by az-vm** [PrestaShop/hummingbird#369]
Hello to all,

I´m testing this new theme, and let me say, it´s a improvement, thank you to all de team working on.

I have notice that when a client go to a product page and change to a size that is dont have stock avaible, it is not updating it, it shows that is available on the message, it don let add to the cart.
To update de message i need to reload the page.

Thank you.

**Comment by NeOMakinG** [comment]
> Hello to all,
> 
> I´m testing this new theme, and let me say, it´s a improvement, thank you to all de team working on.
> 
> I have notice that when a client go to a product page and change to a size that is dont have stock avaible, it is not updating it, it shows that is available on the message, it don let add to the cart. To update de message i need to reload the page.
> 
> Thank you.

You're welcome

Thanks for the report, we'll take a look and fix it 👍

**Comment by az-vm** [comment]
Hello @NeOMakinG 

Thank you, if you need more info about, please let me know.

Regard´s

**Comment by az-vm** [comment]
@NeOMakinG  Thank You!

Now its working and updating on color or size changed in product page.

A nice future to have is when a color or size not available to be in another colour like attach:

<img width="545" alt="Captura de ecrã 2022-09-08, às 11 08 06" src="https://user-images.githubusercontent.com/2712273/189107472-c8229444-fd1c-40fa-a608-3b1078f021f0.png">
