### ISSUE TITLE
FO - User should be able to add Customised product in cart via clickview

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/hummingbird#372]
## Is your feature request related to a problem?
I can't add a customised product _with_ a required customisation to my cart.

<img width="1140" alt="Screenshot 2022-09-16 at 12 21 44" src="https://user-images.githubusercontent.com/16019289/190618343-da5b87fd-5c79-4f1b-b967-909fb91b13e0.png">

## Describe the solution you'd like
I would like to have the field for my customisation directly on the click view popup

## Alternatives you've considered
Go directly on the product page to add customisation and add product to cart

Related to https://github.com/PrestaShop/PrestaShop/issues/29659

**Comment by NeOMakinG** [comment]
![image](https://user-images.githubusercontent.com/14963751/190647200-1fcddfd8-0e51-4c7d-b449-b7ef43aeef63.png)

Already done :)
