### ISSUE TITLE
How to activate scss source-map in dev mode?

### ISSUE THREAD

**Issue by RomainTDC** [PrestaShop/hummingbird#400]
Hi,

In dev mode (npm run dev) how to activate source-map please ?

In /webpack/webpack.development.js  , i try this, but is not fonctionnal ... 

```
exports.developmentConfig = ({ port, publicPath, serverAddress, siteURL, entriesArray }) => ({
  devtool: "source-map", // changed here
  devServer: configureDevServer(serverAddress, publicPath, port, siteURL),
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HotAcceptPlugin({
      test: Object.keys(entriesArray).map(el => `${el}.js`)
    })
  ]
});
```

Thank's !

**Comment by NeOMakinG** [comment]
@RomainTDC You are on the right path, but there is a problem probably with the core:

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/14963751/205923807-a37f88d5-fd3b-428e-85ca-d569a1bd92a9.png">

Access to map files looks forbidden somehow

**Comment by NeOMakinG** [comment]
As It's a core issue, I'll close it on this repository, open it on the core if you want it fixed! Thanks for the feedback btw

**Comment by RTDC** [comment]
Hello,
I’ve resolved the issue — it was the .htaccess file in the theme folder that was blocking access to the theme.css.map file. You just need to modify it as follows:

```
# Apache 2.2
<IfModule !mod_authz_core.c>
    Order deny,allow
    Deny from all
    <Files ~ "(?i)^.*\.(jpg|jpeg|gif|png|bmp|tiff|svg|pdf|mov|mpeg|mp4|avi|mpg|wma|flv|webm|ico|webp|woff|woff2|ttf|eot|otf|css|js|zip|map)$">
        Allow from all
    </Files>
</IfModule>

# Apache 2.4
<IfModule mod_authz_core.c>
    Require all denied
    <Files ~ "(?i)^.*\.(jpg|jpeg|gif|png|bmp|tiff|svg|pdf|mov|mpeg|mp4|avi|mpg|wma|flv|webm|ico|webp|woff|woff2|ttf|eot|otf|css|js|zip|map)$">
        Require all granted
    </Files>
</IfModule>
```
