### ISSUE TITLE
Product Carousel looks like a F1 car!

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/hummingbird#413]
https://github.com/PrestaShop/hummingbird/blob/8a83b963f2ff33f48ec7d1bb60df0ddd816aa289/templates/catalog/_partials/product-cover-thumbnails.tpl#L9

Setting this value to false, makes my PrestaShop (1.7.8.8) product carousel speed like a F1!
![2022-12-21-12-15-19](https://user-images.githubusercontent.com/10741347/208892622-f4063e8f-427b-4414-9d26-6860014a7fb7.gif)

Remove it (gets 5000 as bootstrap default), or set to a value like for example 4000, and we are good

**Comment by NeOMakinG** [comment]
@rodriciru it will be fixed by the QA feedbacks PR don't worry, we can close the issue :p

**Comment by NeOMakinG** [comment]
@rodriciru https://github.com/NeOMakinG/theme-refacto/commit/ec60a30ba95b287e54b47f9382659676ae1701ee#diff-651e390504513bc9c999fa0fbd9295e8be3d52136f41f91a80172136586096f5R9
