### ISSUE TITLE
Install Theme hummingbird problem

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/hummingbird#417]
Hi, i have error: Missing configuration file

**Comment by NeOMakinG** [comment]
I don't know what could cause this, I don't reproduce it at all, maybe you have more information?

**Comment by eveneme** [comment]
When trying to upload a template through the admin panel in zip format. If you upload the template via ftp it works.

**Comment by adamus007p** [comment]
I have the same error. I wanted to install the newest theme in Prestashop 8.0.1
![image](https://user-images.githubusercontent.com/19956106/211429387-07aee7bf-c361-4c9f-8ebf-814c97efe265.png)

Thank you @eveneme I will do it via FTP.

**Comment by SharakPL** [comment]
How do you install the theme?

**Comment by SharakPL** [comment]
OK. The problem is the structure of the archive.

Is: `hummingbird.zip/hummingbird/[theme-files]`
Should be: `hummingbird.zip/[theme-files]`

**Comment by Hlavtox** [comment]
@SharakPL aka Sherlock Holmes for the rescue

**Comment by SharakPL** [comment]
https://github.com/PrestaShop/hummingbird/blob/28a6d147681af036b85d8304441d9bba2929e3a2/.github/workflows/build.yml#L54-L56

I'm not sure how GitHub Actions work but IMO it should be:
```
cd ${{ github.event.repository.name }} 
zip -r ${{ github.event.repository.name }}.zip ./`
```

**Comment by Hlavtox** [comment]
@Progi1984 Could you help us with this? 🙏
