### ISSUE TITLE
bad version inside themes

### ISSUE THREAD

**Issue by adamus007p** [PrestaShop/hummingbird#428]
when I have download the latest theme, upload it [v0.1.2](https://github.com/PrestaShop/hummingbird/releases/tag/v0.1.2)

I see  in Theme & Logo > Theme
![image](https://user-images.githubusercontent.com/19956106/211429952-0dc6592f-514d-4b07-8e30-ae66ad9bdca1.png)

**Comment by Hlavtox** [comment]
We forgot to bump the number, will be fixed for next release. Thanks @adamus007p 👍
