### ISSUE TITLE
Includes front-end JavaScript libraries with known security vulnerabilities

### ISSUE THREAD

**Issue by adamus007p** [PrestaShop/hummingbird#430]
Prestashop 8.0.1 and Hummingbird [v0.1.2](https://github.com/PrestaShop/hummingbird/releases/tag/v0.1.2)

In the  Lighthouse I see:
Includes front-end JavaScript libraries with known security vulnerabilities
[jQuery UI@1.10.3](https://snyk.io/vuln/npm:jquery-ui?lh=1.10.3&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit)
![image](https://user-images.githubusercontent.com/19956106/211431931-51b371fe-17eb-44ef-a601-847039f98b3e.png)

Is is related to hummingbird itself and to Prestashop?

**Comment by TheGera** [comment]
this error is from prestashop not from the theme
public_html//js/jquery/ui/jquery-ui.min.js

They should update it now, since it is a very old library, about 9 years old and they have not paid attention.

https://jqueryui.com/download/
https://www.npmjs.com/package/jquery-ui

**Comment by Hlavtox** [comment]
This needs to be solved on Core side, we will do it for v9 probably. 👍 https://github.com/PrestaShop/PrestaShop/issues/27186

**Comment by NeOMakinG** [comment]
> this error is from prestashop not from the theme
> 
> public_html//js/jquery/ui/jquery-ui.min.js
> 
> 
> 
> They should update it now, since it is a very old library, about 9 years old and they have not paid attention.
> 
> 
> 
> https://jqueryui.com/download/
> 
> https://www.npmjs.com/package/jquery-ui

During more than 3 years, I still paid attention to many things on that project, it usually means that we are lacking of time more than attention, also some subjects are a bit more touchy than what it looks like from the outside

I'm pretty sure I took some hours searching for the best way to update jQuery UI and talked about it, but it's not that simple 😉

**Comment by dennispw** [comment]
Tip: If the theme you are using or developing do not need jQuery UI at all (ps_facetedsearch and/or ps_searchbar by default I *think*) - you could overwrite it and "remove" it within the theme.

Just create these files with an empty comment "`/**/`" (so they are not completely empty and causes a "404" in Chrome):

* `themes/your-theme/js/jquery/ui/jquery-ui.min.js`
* `themes/your-theme/js/jquery/ui/themes/base/minified/jquery.ui.theme.min.css`
* `themes/your-theme/js/jquery/ui/themes/base/minified/jquery-ui.min.css`

I'm not sure if this actually removes the issue from Lighthouse but at least your combined CCC file will be smaller.
