### ISSUE TITLE
broken header

### ISSUE THREAD

**Issue by nizelg** [PrestaShop/hummingbird#434]
I updated from 010 to 020 and header seems have broken css

**Comment by nizelg** [comment]
![image](https://user-images.githubusercontent.com/104589134/212603686-c008bbbe-997f-449d-a98b-147c772a6530.png)

**Comment by Oksydan** [comment]
Hi @nizelg 

How did you upgrade your theme?
Did you just override whole theme folder?

**Comment by nizelg** [comment]
I deleted the old theme and installed new version inside prestashop theme manager

**Comment by Oksydan** [comment]
Look like browser cache problem or CCC for css.
Did you clean your browser cache and prestashop cache? CCC don't clear itself upon files changes.
