### ISSUE TITLE
Shipping Method's İcons are out of box

### ISSUE THREAD

**Issue by nizelg** [PrestaShop/hummingbird#439]
Huge blue image on bottom is how it's normally shown, I added max-width: 100% to image and it's fixed.
Is it just me having this issue?

![image](https://user-images.githubusercontent.com/104589134/214901888-5e13dc01-5e6c-4bdd-a817-33a5a8d5890f.png)

**Comment by nizelg** [comment]
Since I don't know is this just me or general problem i made a child theme to fix the issue.
[child_hummingbird.zip](https://github.com/PrestaShop/hummingbird/files/10511772/child_hummingbird.zip)

**Comment by Hlavtox** [comment]
Hi @nizelg, add img-fluid 😎
Can you make a PR for it?

**Comment by nizelg** [comment]
it's on me
