### ISSUE TITLE
Can't add new adress with hummingbird theme

### ISSUE THREAD

**Issue by nizelg** [PrestaShop/hummingbird#441]
Problem is when write address information and continue to shipping carrier selection, it just reloads and asking the adress information again.
I tried on fresh prestashop with current develop branch.

https://user-images.githubusercontent.com/104589134/215178215-1ea1312e-b2b4-4e22-94a7-3b281960ab4d.mp4

||Red text in end saying "No suitable carrier for your location", its ok||

**Comment by nizelg** [comment]
I just saw this commit and what i did was just reversing it, I don't think this issue is easy to fix as i thought.
https://github.com/PrestaShop/hummingbird/commit/d26f38c4611b24c35d144f4112ef8761e1d48d54

**Comment by Hlavtox** [comment]
@nizelg Yes, I found this also few days ago (added here https://github.com/PrestaShop/hummingbird/issues/409). I also can't add a new address for some reason in my account section, not sure what is happening. 🤷

**Comment by TheGera** [comment]
The problem happened when [418](https://github.com/PrestaShop/hummingbird/pull/418) I ignored changes in theme.js and the addresses work

**Comment by nizelg** [comment]
I confirm that problem is [theme.ts in 418](https://github.com/PrestaShop/hummingbird/pull/418/files#diff-5a544dbb2b4b4b9bc07e2ecff53b8d386d93e3fa00f869bcac52128ae43a72e8) Thank you TheGera

**Comment by Hlavtox** [comment]
@NeOMakinG Bro do you think you could check this? We need to revert that token change or improve it, like @nizelg done. 😞 It broke address forms.

BTW, @nizelg, these buttons can also be on product pages in accessories, in crosselling on shopping cart page etc. We must do it properly. 😛

**Comment by nizelg** [comment]
Looks like i've hit a roadblock xd, adding items to the card on the product page isn't working as it should. I'm thinking that adding the ID to all the buttons might be the way to go, it's worth a shot, right?

**Comment by nizelg** [comment]
I've been casually browsing the site and adding items to my cart, and it seems to be working fine. I was cleared my cache, but the issue seems fixed

https://user-images.githubusercontent.com/104589134/215270945-6cbb3289-1af7-4573-a6cc-1a032708e91c.mp4

**Comment by Hlavtox** [comment]
Fixed
