### ISSUE TITLE
Bugs in templates with classnames modifier

### ISSUE THREAD

**Issue by jirbel** [PrestaShop/hummingbird#449]
When using classnames modifier in tpl, every class is also being modified (https://devdocs.prestashop-project.org/8/development/components/smarty-extensions/#classname)

For example when you pass class like `step--current`, the result will be `step-current`

So if we wanna have classes in array, we need change 
`{[]|classnames}` 
to something like 
`{implode(' ',array_keys(array_filter([])))`

I could search all usages and make PR if you think this is good solution.

**Comment by kpodemski** [comment]
Hello @jirbel 

which version of PrestaShop do you use with Hummingbird?

**Comment by SharakPL** [comment]
One more reason to not use BEM 😉

**Comment by jirbel** [comment]
@kpodemski Sorry, I missed yout answer. Looks like you were right. This is fixed in prestashop 8. I was using 1.7 before.
