### ISSUE TITLE
homepage mini add to cart button not following store catalog mode Setting

### ISSUE THREAD

**Issue by nizelg** [PrestaShop/hummingbird#455]

**Comment by nizelg** [comment]
disable sellings (catalog mode on) in bo, cart buttons will di

**Comment by nizelg** [comment]
Template compilation issue, recompile.

**Comment by Hlavtox** [comment]
@sneko Do you see it on homepage or in a category?

The modules on homepage are caching the HTML, so it can contain outdated data.

**Comment by sneko** [comment]
@Hlavtox on homepage. (sorry for the late answer...)

I tried to clear the cache from the Performance panel, but still there whereas in the "popup" there is none, nor onto the product page. Maybe there is another cache not deleted by the Performance panel?
