### ISSUE TITLE
Wrong images used for subcategories

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/hummingbird#467]
That's how it looks now:

![obraz](https://user-images.githubusercontent.com/5007456/222727962-3923def6-0a66-4672-8041-ea15d5cd340b.png)

subcategories.tpl uses `large` image which is main `category_cover` (2000x400 px). The category's thumbnail

![obraz](https://user-images.githubusercontent.com/5007456/222734234-00b7ceba-6508-4bf2-b797-78a945f96d3e.png)
is generated only as `small` so that's what should be used.

There are several problems with category images, but they need to be fixed in PrestaShop repo. For example:
- if only thumbnail is used then none of the images (including thumbnail) is available ($subcategory.image is null) so it can't be used even though it's set
- thumbnail image can't be deleted

**Comment by Hlavtox** [comment]
@SharakPL There is a mess in it, we need to fix it - https://github.com/PrestaShop/PrestaShop/issues/30520
