### ISSUE TITLE
"Register with password" is shown even if user is registered in final order page

### ISSUE THREAD

**Issue by nizelg** [PrestaShop/hummingbird#472]
This shouldn't be here if user is registered while ordering or logged in.
![image](https://user-images.githubusercontent.com/104589134/224455129-7c0f41f1-a9a4-4cb8-ae6c-37891f3d9d58.png)

**Comment by nizelg** [comment]
could anyone please assign this issue to me? It's on me

**Comment by Hlavtox** [comment]
@nizelg I think a wrong variable is used, check the condition in classic please 👍

**Comment by nizelg** [comment]
Thanks for your thoughts, yes there was a wrong variable and an another wrong variable in a condition. i'll open pr request as soon as i test it.However i saw that; latest classic theme in prestashop/classic-theme using order_customer & registered_customer_exists  which caused error in 1.7.8.8 but local classic theme using customer & customer.is_guest13:31, 11 Mart 2023, Daniel Hlavacek ***@***.***>:
@nizelg I think a wrong variable is used, check the condition in classic please 👍

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Yandex Mail mobil uygulamasından gönderildi
