### ISSUE TITLE
If category image don't exist, this will throw a null on php logs

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/hummingbird#476]
https://github.com/PrestaShop/hummingbird/blob/e1429f34253756117e4f669d48e569748fec9cd1/templates/catalog/_partials/category-header.tpl#L12

I think this only needs  {if $category.image} because if  {if $category.image} don't exist, the values of large and large.url it will be null or undefined
https://github.com/PrestaShop/hummingbird/pull/477

**Comment by rodriciru** [comment]
https://github.com/PrestaShop/hummingbird/pull/477

**Comment by tswfi** [comment]
I can't replicate this on ps 8.1.2 and current develop branch of hummingbird.
