### ISSUE TITLE
[FO]  FILTERING - Resize screen to mobile

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/hummingbird#483]
Resize screen to mobile: 

- [ ]  open filters, resize screen back to desktop. ➡️ Empty modal is open.
- [ ]  resize it back ➡️ Price slider doesn't work.

**Comment by ga-devfront** [comment]
@Zoefinders we are not able to reproduce this bug because we didn't show the Price slider in filters :  
>  resize it back -> Price slider doesn't work.
