### ISSUE TITLE
[UNFINISHED THINGS]  Style category left column module - category tree

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/hummingbird#490]
Style this module properly - https://github.com/PrestaShop/ps_categorytree/

**Comment by Zoefinders** [comment]
![Image](https://user-images.githubusercontent.com/99200820/236132935-29a436fd-5875-4a22-96e8-7c06540c1f90.png)

**Comment by ElodieOS** [comment]
Hello @Zoefinders!

This is my proposition 😊

![image](https://github.com/PrestaShop/hummingbird/assets/113457393/70c6f310-72eb-44f0-8db3-cc958ed6babd)
