### ISSUE TITLE
[UNFINISHED THINGS]  - Style other prices like unit prices and ecotax and others

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/hummingbird#491]
![Image](https://user-images.githubusercontent.com/99200820/234570701-fc3fba9c-0e7c-41f6-8d61-4cc40cdbfe8b.png)
![Image](https://user-images.githubusercontent.com/99200820/234570700-54666c97-2260-4c69-aacd-c231d43c4067.png)

**Comment by Hlavtox** [comment]
Reduced price is already styled. ✅ 

![Snímek obrazovky 2023-05-04 090320](https://user-images.githubusercontent.com/6097524/236133452-2110f9c8-e984-4699-a9cc-eb767d2c3331.jpg)

**Comment by Zoefinders** [comment]
Thanks @ElodieOS for me it's good ! @Hlavtox what do you think ?

**Comment by ElodieOS** [comment]
Hi @Zoefinders! 
This is my proposition ☺️ 

![image](https://github.com/PrestaShop/hummingbird/assets/113457393/b342eae1-4d34-4b6f-9f8f-933fcdb4f498)
