### ISSUE TITLE
Product image slider make a bug when sliding rendering image bigger during transition.

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/hummingbird#504]
Product image slider make a bug when sliding by rendering image bigger during few milliseconds. This is due to the size of the image that is smaller to his container and make, and the slider make it 100% width during the image translate, so this creates a little shift. (More visible with screens < 992px & > 767px)

**Comment by GytisZum** [comment]
This issue was fixed with #436 pull request.
