### ISSUE TITLE
[DESKTOP - Cart Page] Cart

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/hummingbird#51]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2
Responsive's issue: https://github.com/PrestaShop/theme-refacto/issues/52

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=383%3A12713)

#### UX and design explanations
- As a customer, it's important to be able to edit the card directly on the cart page. If this isn't possible, the customer will have to add the same product to the cart but with a different size, color, etc
- Size and color can be changed by clicking on the dropdown
- Also, quantity remains editable
- The "Remove" button has been placed in the bottom where other actions can be next to it (e.g. "Add to Wishlist" button if the module is enabled)

#### Mockup
![desktop - cart page](https://user-images.githubusercontent.com/54888056/136406082-ecad61cb-5005-497d-b515-9db98791dd31.png)

**Comment by Hlavtox** [comment]
@prestascott Hi! Scott, can you please add highlighted vouchers to the figma sketches, if they exist?

Create a cart rule without a code, set proper validity, make voucher amount like 9999999 and set it to discount the order by whatever. On the first tab of the voucher, enable "Highlight voucher". Then go to cart and you should see something like "take advantage of our offers".

Thanks!

**Comment by Hlavtox** [comment]
![Výstřižek](https://user-images.githubusercontent.com/6097524/143603099-3c2c9aff-5e24-4c21-8ee5-8ef479add080.JPG)

**Comment by NeOMakinG** [comment]
Promo code/vouchers is the only thing left on this issue

**Comment by NeOMakinG** [comment]
We stylized it, I guess this can be reopened when we will be checking with Product/UX at the end in case we've something else to do!
