### ISSUE TITLE
Checkout shopping cart prices showing wrongly

### ISSUE THREAD

**Issue by kacpirdt** [PrestaShop/hummingbird#523]
Add something to shopping cart without discount and go to checkout. There is regular price strikethrough even if not discounted price.

![Screenshot 2023-06-27 at 09 32 35](https://github.com/PrestaShop/hummingbird/assets/135665287/1d94d097-5d56-4830-8d61-756f392810be)

**Comment by SharakPL** [comment]
Hi @kacpirdt . Thanks for reporting the issue but more information would be helpful. Which prestashop version/branch did you use? Which version of PHP? Did you use non native modules that could impact the cart or products?

**Comment by kacpirdt** [comment]
@SharakPL The screenshot is made PS 8.1 beta, but this issue is still visible also final 8.1. I downloaded Hummingbird latest code.

**Comment by SharakPL** [comment]
Fixed in #535
