### ISSUE TITLE
[Shopping Cart] the price is displayed twice as if there was a discount

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/hummingbird#535]
### Describe the bug and add attachments
the price is displayed twice as if there was a discount, see the attached screenshot below:

![image](https://github.com/PrestaShop/hummingbird/assets/23308427/4e3901f8-7889-4f39-bffc-1b7515bc4142)

### Expected behavior
If there's no discount, the price should be displayed once as Classic theme, see the attached screenshot below:

![image](https://github.com/PrestaShop/hummingbird/assets/23308427/fe1cfa93-5e7f-4e68-8ba9-220c7ef5650f)

### Steps to reproduce

1. FO>add some products without discount in the cart
2. Click on Proceed to checkout
3. See error > all prices are displayed twice as if there's was a discount

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
This issue is fixed on develop branch.

<img width="708" alt="Screenshot 2024-03-29 at 11 06 37" src="https://github.com/PrestaShop/hummingbird/assets/16019289/4ea5c160-771e-4b9b-b3df-43f076d91de7">


So I'm closing it.
