### ISSUE TITLE
Variants display problem on product page

### ISSUE THREAD

**Issue by ash-f** [PrestaShop/hummingbird#559]
This style results the variants attached each other without any spaces.
Which not looking good and hard to read. also it doesn't wraps when they are many.
```
.page-product .product__variants .variant ul {
    align-items: center;
    display: flex;
}
```

So it should be something like this.
```
.page-product .product__variants .variant ul {
    align-items: center;
    display: flex;
    gap: 20px;
    flex-wrap: wrap;
}
```

**Comment by tswfi** [comment]
Can you explain how to replicate this?

I don't see anything strange with the variants

![image](https://github.com/PrestaShop/hummingbird/assets/1352132/6b6171d3-ec9c-4f7c-a7f9-2117ec237fd0)

**Comment by florine2623** [comment]
@ash-f , could you explicit your issue ? add screenshots ?
