### ISSUE TITLE
Unable to run "npm run build"

### ISSUE THREAD

**Issue by alisamie97** [PrestaShop/hummingbird#561]
After I cloned the repo, I ran `npm ci` and then as mentioned in the readme file I made a `.env` file.
Finally, I tried to run `npm run build` and it failed with the following error:
```
Embedded Dart Sass couldn't find the embedded compiler executable. Please make sure the optional dependency sass-embedded-linux-x64 is installed in node_modules.
```

I searched for it and fixed it as mentioned here: https://stackoverflow.com/a/72495069/5864034

**Comment by SharakPL** [comment]
How did you install your shop and Hummingbird theme? What Node and NPM versions do you have installed on your development environment? Is it WSL?

**Comment by alisamie97** [comment]
im using a docker container in ubuntu
I cloned the theme into themes/ directory, then I switched to the theme in BO

**Comment by tswfi** [comment]
Can we activate "discussions" for this kind of support questions? 

I have not had any problems running `npm run build`
