### ISSUE TITLE
Mobile product list changes between one product per "line" and two products per line

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/hummingbird#564]
open a category page, defaults to two products side by side

![image](https://github.com/PrestaShop/hummingbird/assets/1352132/568fa62c-1b42-4399-b127-3e2cac16efbf)

use pager to go one page forward and one page back (ajax query replaces content). Now it is one product per page

![image](https://github.com/PrestaShop/hummingbird/assets/1352132/61ba05b9-5501-41eb-ad65-f25c0e3de942)

and if you got to page 3 with the paging buttons, you will see one product per line. but if you reload the page completely it will again be two products side by side.

**Comment by tswfi** [comment]
https://github.com/PrestaShop/hummingbird/blob/986d1a2f7f67bc865774b9500b18051160932ffe/templates/catalog/_partials/productlist.tpl#L5

productClasses are defined differently on full page load and ajax content

**Comment by Hlavtox** [comment]
Correct is two columns ;-)
