### ISSUE TITLE
Build command fails if there is no .env file with a wrong message

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/hummingbird#580]
If you run `npm run build` without `.env` you have this error:

```
npm run build

> prestashop-hummingbird-dev-tools@0.1.5 build
> webpack --progress --mode=production

Your .env file not exits. Read getting started section in documentation for more information https://devdocs.prestashop.com/8/themes/getting-started/.
```

but there is nothing about Hummingbird in the developer documentation.

**Comment by leemyongpakva** [comment]
In fact, the instruction stays at https://github.com/PrestaShop/hummingbird?tab=readme-ov-file#how-to-build-assets
