### ISSUE TITLE
Incorporate improvements for user authentication forms

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/hummingbird#582]
More details:
https://evilmartians.com/chronicles/html-best-practices-for-login-and-signup-forms

Details to be specified.

**Comment by yannicka** [comment]
For the first point, here is the current state (and in brackets what I propose):

## Login

- Email: `autocomplete="email"` (=> `autocomplete="username"`)
- Password: `autocomplete="current-password"` (=> `autocomplete="current-password"`)

## Registration

- Email: *nothing* (=> `autocomplete="username"`)
- Password: *nothing* (=> `autocomplete="new-password"`)

## Forgotten password

### Ask email scren

- Email: *nothing* (=> `autocomplete="username"`)

### New password screen

- New password: `autocomplete="off"` (=> `autocomplete="new-password"`)
- Repeat password: `autocomplete="off"` (=> `autocomplete="new-password"`)

## Identity

- Email: `autocomplete="off"` (=> `autocomplete="username"`)
- Current password: *nothing* (=> `autocomplete="off"` OR `autocomplete="current-password"`)
- New password: `autocomplete="off"` (=> `autocomplete="new-password"` OR keep the same value `off`)

Is it any good? I'm not sure which is preferable between "username" and "email".

**Comment by yannicka** [comment]
Points 2, 3, 4, 5, 6, 7 and 9 seem good.

Point 8 ("Mark invalid fields for screen-readers") is not good.

I don't know about points 10 and 11.

I haven't checked in detail, but here's what emerges from a (very) quick analysis.

**Comment by kpodemski** [comment]
Hello @yannicka 

> I'm not sure which is preferable between "username" and "email".

I think it would be email, and from what I remember this was the main improvement I wanted to include to forms in Hummingbird.

> I don't know about points 10 and 11.

10 - I think we're good. 11 - this is worth checking, every single action that takes time and is being sent via AJAX should indicate that something is going on, I think it works better in Hummingbird but I haven't checked everything

**Comment by yannicka** [comment]
So:
- Login screen: OK
- Register screen: It is not possible to make the change in the theme. You need to make the change on PrestaShop.
- Forgotten password screens: fixed by #591 (if merged)
- Identity: same as register screen

**Comment by yannicka** [comment]
We can also go a little further with the other autocomplete values for the first name, surname, address, postcode, telephone number, etc. (on PrestaShop code)
