### ISSUE TITLE
Carrier extra content not visible when changing between order steps from "header"

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/hummingbird#589]
not sure yet what happens, but :

```
<div class="carrier__extra-content-wrapper  carrier__extra-content-wrapper--active  js-carrier-extra-content" style="max-height: 0px;">
```

is applied to all carriers, even the selected one. This makes it impossible to see the extra content for the selected carrier if you switch steps either from the links at top of the order flow or from the "edit shipping" button in order-summary from payment step.

Steps to reproduce: add carrier extra content (write a test module that adds something in the carrierExtraContent hook), activate "show order summary", go forward in the order process until on the payment step. now click on "shipping" from the links above or shipping method "edit" button in order-summary.  Carrier selection is shown but extra content is not. switching carrier at this point does show it again (something somewhere calculates max-height for the div).

**Comment by Hlavtox** [comment]
➡️ last change was this - https://github.com/PrestaShop/hummingbird/pull/496/files

**Comment by tswfi** [comment]
uh, was I testing on an older version.. sorry for the noise. I'll close this and if I can replicate again I'll open new issues.
