### ISSUE TITLE
hummingbird - In Checkout process, Personal Information tab, wording in incorrect

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/hummingbird#590]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Wording is incorrect, seen with @ElodieOS.

It is now "New customer", it should be "Order as guest"

<img width="786" alt="Screenshot 2024-02-08 at 10 51 38" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/3b646ef2-8d58-471c-867e-f45d22f960c8">

### Expected behavior

Should be like it was in classic theme :

<img width="735" alt="Screenshot 2024-02-08 at 10 51 43" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/94abaec5-206d-4d02-8710-238d33c03a5e">

### Steps to reproduce

1. Install hummingbird theme
2. Go to FO > Add a product to cart > Proceed to checkout
3. See in Step 1 - Personal Information, wording is incorrect :x:

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by Julievrz** [comment]
We're not saying that a customer isn't a customer. We are saying that the position on the page, next to the "Order as Guest" label, can be confusing, as it appears that we are suggesting that the user create a new account.

**Comment by SharakPL** [comment]
> I agree that we could also remove the tabs and add the option to sign in or create an account elsewhere.

The difference between a guest order and creating an account is just filling up the password field so a simple switch for toggling password, like I showed before, should be enough.
___
Nice improvement here (unless already implemented, I'm not sure) would be to suggest creating an account if email used for guest order was used before for another guest order:

> It looks like it's not your first order on this shop. Would you like to create an account?
> 
> Here are the benefits:
> + Quicker orders - no need to fill the personal data every time
> + Keeping order history
> + Creating personal wishlists
> + Occasional special offers for registered customers
>
>  [ Create account now ]
>

**Comment by Hlavtox** [comment]
@SharakPL That's a nice idea, but also bit of an information disclosure. Imagine www.somenastythings.com and the form showing you if you ordered before or not. :-)

**Comment by SharakPL** [comment]
@Hlavtox I don't see the danger here, but just in case we could compare both email and last name
