### ISSUE TITLE
Release v0.1.7

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/hummingbird#596]
Objective of the release:
- Share the bug fix and feature merged from the past 8 months 
- Ease the QA autom to work on a more recent version to launch the new UI test incoming

**Comment by WahbiPS** [comment]
https://github.com/PrestaShop/hummingbird/pull/600

**Comment by tswfi** [comment]
this can be closed. 0.2.0 was released https://github.com/PrestaShop/hummingbird/releases/tag/v0.2.0
