### ISSUE TITLE
Replace "else if" smarty conditions by "elseif" as officially recommanded

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/hummingbird#604]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As recommended by [Smarty official documentation](https://www.smarty.net/docs/en/language.function.if.tpl) an "else-if" condition must be write `{elseif}` (without space between `else` and `if`).

But currently, an `else if` syntax (with a space between `else` and `if`) is currently used:
- 3 times in 2 files into last version of Classic theme:
https://github.com/search?q=repo%3APrestaShop%2Fclassic-theme+%22%7Belse+if%22&type=code
- 4 times in 3 files into last version of Hummingbird theme:
https://github.com/search?q=repo%3APrestaShop%2Fhummingbird%20%22%7Belse%20if%22&type=code

In comparison, `elseif` syntax (without space between `else` and `if`) is currently used:
- 28 times in 22 files into last version of Classic theme:
https://github.com/search?q=repo%3APrestaShop%2Fclassic-theme+%7Belseif&type=code
- 35 times in 19 files into last version of Hummingbird theme:
https://github.com/search?q=repo%3APrestaShop%2Fhummingbird+%22%7Belseif%22&type=code

Not checked into every Smarty template files (modules, other themes…)

### Expected behavior

A uniform smarty else-if syntax following official recommendation everywhere (in each smarty template ".tpl" files of the whole project).

### Steps to reproduce

1. Search for "{else if" in Classic theme codebase

### PrestaShop version(s) where the bug happened

1.7.x, 8.x

### PHP version(s) where the bug happened

8.1

**Comment by Klemart3D** [comment]
Hi @MatShir , thank you.
I made 2 pull requests :
- For Classic theme: https://github.com/PrestaShop/classic-theme/pull/142
- For Hummingbird theme: https://github.com/PrestaShop/hummingbird/pull/605

**Comment by SharakPL** [comment]
Fixed
