### ISSUE TITLE
Unusable menu dropdown when store logo is tall

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/hummingbird#624]
- Related to https://github.com/PrestaShop/hummingbird/issues/546
Tested with this file :
<img width="190" alt="Screenshot 2024-02-23 at 14 59 44" src="https://github.com/PrestaShop/hummingbird/assets/16019289/042a1a94-1b18-44fa-a909-3ed7443904a9">

Here's the result :x:

https://github.com/PrestaShop/hummingbird/assets/16019289/c8d1d6ad-7f02-4b0f-9c68-51f09b7b150c

**Comment by SharakPL** [comment]
This again? 🫤

**Comment by SharakPL** [comment]
Duplicate. Already fixed in #606

**Comment by nicosomb** [comment]
The bug was detected by @florine2623 in #600, after #606 was merged... S

**Comment by SharakPL** [comment]
@nicosomb no, it wasn't 😉 Her report in #600 was 3 months ago.

**Comment by nicosomb** [comment]
sorry for the noise
