### ISSUE TITLE
For the module productcomments, the stars are not displayed on category page

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/hummingbird#625]
- Related to https://github.com/PrestaShop/hummingbird/pull/568
For the module productcomments, the stars are not displayed on category page :x:

https://github.com/PrestaShop/hummingbird/assets/16019289/a0d79724-38e1-486a-8384-64c585d6a15e

**Comment by SharakPL** [comment]
Are you sure you build the assets properly and have productcomments module at min ver 6.0.3?

**Comment by nicosomb** [comment]
ping @florine2623 who detected the issue.

**Comment by SharakPL** [comment]
It looks like your issues are duplicates of already fixed ones.
