### ISSUE TITLE
[DESKTOP - Checkout Page] Step 2: Shipping information 

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/hummingbird#8]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=2351%3A24213)

**Comment by NeOMakinG** [comment]
I guess this is done, if there are some things to polish, let's see this after product review
